[package]
name = "arctis-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.93"
solana-transaction-status-client-types = "2.1.6"